application: stromcekakodarcek
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /fonts
  static_dir: fonts  
  
- url: /stylesheets
  static_dir: stylesheets

- url: /img
  static_dir: img
  
- url: /js
  static_dir: js
  
- url: /.*
  script: main.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  
builtins:
- remote_api: on